---
# SPDX-FileCopyrightText: © 2025 Olivier Meunier <olivier@neokraft.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

routes:
  /oauth/client:
    post:
      tags: [oauth]
      $merge:
        - "traits.yaml#public"

      summary: Client Registration
      description: |
        This route creates a new OAuth client. You must create a new client before you can request permissions and receive a token.

        Please refer to the [Client Registration Documentation](#overview--client-registration) for more details.

        This route implements [RFC 7591: OAuth 2.0 Dynamic Client Registration Protocol](https://datatracker.ietf.org/doc/html/rfc7591).

        Note: checks on `token_endpoint_auth_method` and `response_types` are enforced but their respective values are not used internaly.

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/oauthClientCreate"

      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/oauthClientResponse"

        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/oauthError"

  /oauth/token:
    post:
      tags: [oauth]
      $merge:
        - "traits.yaml#public"

      summary: Access Token
      description: |
        A client must call this route once it received the necessary information from the
        redirect URI generated by the authorization route.

        Please refer to:

        - [OAuth Authorization Code Flow](#overview--oauth-authorization-code-flow) for details about the authorization code flow
        - [OAuth Device Code Flow](#overview--oauth-device-code-flow) for details about the device code flow

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/oauthTokenCreate"

      responses:
        "201":
          description: Access Token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/oauthTokenResponse"

        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/oauthError"

  /oauth/device:
    post:
      tags: [oauth]
      $merge:
        - "traits.yaml#public"

      summary: Device Authorization
      description: |
        This route is the device authorization request. A client must call it first,
        with its client ID and a scope list it wants to grant a device.

        Please refer to [OAuth Device Code Flow](#overview--oauth-device-code-flow) for more information.

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/oauthDeviceCreate"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/oauthDeviceCreate"

      responses:
        200:
          description: Device Authorization Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/oauthDevice"

        400:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/oauthError"

  /oauth/revoke:
    post:
      tags: [oauth]
      $merge:
        - "traits.yaml#.authenticated"

      summary: Revoke Token
      description: |
        This route lets a client revokes an access token. It must authenticate using the same
        access token than the one provided in the request body.

        You can use this route if you want to provide a log-out option to users.

      requestBody:
        content:
          application/json:
            schema:
              required: [token]
              properties:
                token:
                  type: string
                  maxLength: 64
                  description: Access token to revoke

      responses:
        "200":
          description: Access token revoked

        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/oauthError"